name: Create stable release

on:
  workflow_dispatch:

jobs:
  release:
    name: Create release
    runs-on: macos-15
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        path: source
        token: ${{ secrets.SDK_BOT_ACCESS_TOKEN }}
        fetch-depth: 0
        fetch-tags: true

    - name: Checkout scripts
      uses: actions/checkout@v4
      with:
        path: scripts
        repository: moengage/sdk-automation-scripts
        token: ${{ secrets.SDK_BOT_ACCESS_TOKEN }}
        fetch-depth: 0
        fetch-tags: true

    - name: Setup keychain
      uses: ./scripts/actions/ios-keychain-setup
      env:
        MO_CERTIFICATE_IDENTITY: ${{ secrets.MO_CERTIFICATE_IDENTITY }}
        MO_CERTIFICATE_PASSWORD: ${{ secrets.MO_CERTIFICATE_PASSWORD }}
        MO_CERTIFICATE_BASE64: ${{ secrets.MO_CERTIFICATE_BASE64 }}

    - name: Create release
      uses: ./scripts/actions/ios-sdk-client-release
      with:
        dir: source
      env:
        GITHUB_TOKEN: ${{ secrets.SDK_BOT_ACCESS_TOKEN }}
        MO_CERTIFICATE_IDENTITY: ${{ secrets.MO_CERTIFICATE_IDENTITY }}

    - name: Delete keychain
      if: always()
      uses: ./scripts/actions/ios-keychain-delete
