name: Run tests

on:
  pull_request:
  workflow_dispatch:
    inputs:
      environment_variables:
        description: Custom space separated environment variables, that can be used for package resolution
        type: string
        required: false
        default: ''

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  swift-package:
    name: Build and run tests for Swift Package Manager on ${{ matrix.destination }}
    runs-on: macos-latest
    strategy:
      matrix:
        destination: [iOS Simulator, tvOS Simulator]

    steps:
    - name: Set custom environment variables
      if: github.event_name == 'workflow_dispatch'
      run: |
        VARIABLES=(${{ inputs.environment_variables }})
        for variable in ${VARIABLES[@]}; do
          echo "$variable" >> $GITHUB_ENV
        done

    - name: Checkout source repository
      uses: actions/checkout@v4

    - name: Setup Xcode version
      uses: maxim-lobanov/setup-xcode@v1.4.1
      with:
        xcode-version: '15.4'

    - name: Build and Run tests
      run: xcodebuild test -destination "platform=${{ matrix.destination }}" -scheme Segment-MoEngage
